//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOCos_V1
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Administrador
    {
        public int idAdministrador { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public IEnumerable<SelectListItem> UserList { get; set; }
        public string Tipo { get; set; }
    
        public virtual Usuario Usuario { get; set; }

    }
}
