//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOCos_V1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.Web.Mvc;

    public partial class Alumnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumnos()
        {
            this.HistorialAsesoria = new HashSet<HistorialAsesoria>();
        }
    
        public int idAlumno { get; set; }
        [DisplayName("Nombre(s)")]

        public Nullable<int> idUsuario { get; set; }
        public IEnumerable<SelectListItem> UserList { get; set; }

        [DisplayName( "Cuatrimestre")]
        public Nullable<int> idCuatrimestre { get; set; }
        public IEnumerable<SelectListItem> UserCuatri { get; set; }

        [DisplayName ( "Grupo")]
        public Nullable<int> idGrupo { get; set; }
        public IEnumerable<SelectListItem> UserGrupo { get; set; }

        [Required(ErrorMessage = "{0} es requerido")]
        [MinLength(4, ErrorMessage = "{0} Debe terner una logitud mayor o igual a 4 caracteres")]
        [DisplayName("Matricula")]
        public string Matricula { get; set; }
    
        public virtual Cuatrimestre Cuatrimestre { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialAsesoria> HistorialAsesoria { get; set; }
    }
}
