//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOCos_V1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Documentos
    {
        public int idDocumento { get; set; }
        public Nullable<int> idTema { get; set; }

        [Required(ErrorMessage = "{0} es requerido")]
        [DisplayName("Nombre")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "{0} es requerido")]
        [DisplayName("Link")]
        public string Link { get; set; }
    
        public virtual Temas Temas { get; set; }
    }
}
