//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOCos_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialAsesoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HistorialAsesoria()
        {
            this.Portafolio = new HashSet<Portafolio>();
        }
    
        public int idHistorial { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> idProfesor { get; set; }
        public Nullable<int> idAlumno { get; set; }
        public Nullable<int> idTema { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Profesor Profesor { get; set; }
        public virtual Temas Temas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Portafolio> Portafolio { get; set; }
    }
}
