//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOCos_V1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mocOS_BDEntities : DbContext
    {
        public mocOS_BDEntities()
            : base("name=mocOS_BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<Alumnos> Alumnos { get; set; }
        public virtual DbSet<Clase> Clase { get; set; }
        public virtual DbSet<Cuatrimestre> Cuatrimestre { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<HistorialAsesoria> HistorialAsesoria { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<Portafolio> Portafolio { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Temas> Temas { get; set; }
        public virtual DbSet<TiposUsuarios> TiposUsuarios { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Documentos> Documentos { get; set; }
    }
}
