//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOCos_V1
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    public partial class Profesor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesor()
        {
            this.HistorialAsesoria = new HashSet<HistorialAsesoria>();
            this.Materia = new HashSet<Materia>();
        }
    
        public int idProfesor { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string Cubo { get; set; }
        public Nullable<int> idMateriaEnseña { get; set; }
        public IEnumerable<SelectListItem> UserEnseña { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialAsesoria> HistorialAsesoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materia> Materia { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Materia Materia1 { get; set; }
    }
}
