//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOCos_V1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Administrador = new HashSet<Administrador>();
            this.Alumnos = new HashSet<Alumnos>();
            this.Profesor = new HashSet<Profesor>();
        }
    
        public int idUsuario { get; set; }
        public string Nombre { get; set; }
        public string Contrasena { get; set; }
        public string ApellidoMaterno { get; set; }
        public string ApellidoPaterno { get; set; }
        public string Dirección { get; set; }
        public string Telefono { get; set; }
        public string Genero { get; set; }
        public Nullable<System.DateTime> FechaDeNacimiento { get; set; }
        public byte[] FotoPerfil { get; set; }
        public Nullable<int> idTipoUsuario { get; set; }
        public string Correo { get; set; }
        public string idToken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Administrador> Administrador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumnos> Alumnos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profesor> Profesor { get; set; }
        public virtual TiposUsuarios TiposUsuarios { get; set; }
    }
}
